// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

export type ShareProject = {
  projectId: string,
  userId: string,
  role: string,
  canEdit: boolean,
  canShare: boolean,
  canDelete: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ShareProject {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("projectId", AlgebraicType.createStringType()),
      new ProductTypeElement("userId", AlgebraicType.createStringType()),
      new ProductTypeElement("role", AlgebraicType.createStringType()),
      new ProductTypeElement("canEdit", AlgebraicType.createBoolType()),
      new ProductTypeElement("canShare", AlgebraicType.createBoolType()),
      new ProductTypeElement("canDelete", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ShareProject): void {
    ShareProject.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ShareProject {
    return ShareProject.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

